FROM node:latest

MAINTAINER adityasahu <aditya.sahu@avalara.com>

WORKDIR /usr/home/docker-first/

RUN apt-get -y update

RUN npm install -g http-server

RUN npm install -g ember-cli

CMD ["ember", "-s"]